### PR TITLE
.bot improvements

### PR DESCRIPTION
**Pull request by ar1a**
This pr is pretty sizable, a lot of stuff was referenced from splewis' csgo practice mode plugin.

The biggest changes are bots now don't move when you bump into them, because they spawn on the enemy team. To remedy the fact noclip was required to get the player out, we set the collisions on both player and bot to be noblock until they're no longer colliding.

I also added a much needed `buddha` to prac.cfg, which should be automatically unpracc'd via the `sv_cheats 0`.

### CODE REVIEW

**Comment by mrc4tt** [comment]
After testing this on a private server.

If you swap under practice with `.t/.ct`
It is no longer possible to use `.bot`

As no bots have been added
`[MatchZy] Cannot add bots, team is full! Use .nobots to remove the current bots.`

**Comment by ar1a** [comment]
> After testing this on a private server.
> 
> If you swap under practice with `.t/.ct` It is no longer possible to use `.bot`
> 
> **Edit**: My bad, I had overlooked that I didn't change
> 
> `else if (player.TeamNum == 3)` - my mistake.

If you want a dll with both of my PRs applied, here you go 
[MatchZy.zip](https://github.com/shobhit-pathak/MatchZy/files/13498498/MatchZy.zip)

**Comment by shobhit-pathak** [comment]
Hey, thanks for the PR!

Is there any specific reason why do we need this approach where we modify collision groups?
I mean the current approach that I'm using is also not great, but serves the purpose for now so is there any bug/issue here?

I had also planned to improve `.bot` logic as now we have `CreateEntityByName` in CSSharp that means instead of using `bot_add_t/ct`, we can create a bot entity and teleport it.

For the buddha part, `.god` command was added by @DEAFPS so that user can enable god-mode for them if they want so that it is not enabled by default.

**Comment by ar1a** [comment]
> Is there any specific reason why do we need this approach where we modify collision groups?

- Bots on your team will move if you bump in to them, bot on the enemy team won't.
- You can't damage teammates in warmup so for that reason you've set `mp_teammates_are_enemies true`, which makes practicing with the team quite difficult because you have no idea where anyone is
- Spawning an enemy bot in your position means you can't move, so you have to noclip out of them
- To solve the noclip issue, the [csgo practice mode plugin modified collisions](https://github.com/splewis/csgo-practice-mode/blob/e77a7c7140f0b16dd00c6d345395ed9a90b02bb0/scripting/practicemode/bots.sp#L644-L668). I liked that solution the best as a very active user of practice mode, so I implemented it. 

> I had also planned to improve .bot logic as now we have CreateEntityByName in CSSharp that means instead of using bot_add_t/ct, we can create a bot entity and teleport it.

This sounds great, although we still have the prior collision issues, so this PR is futureproof.

> For the buddha part, .god command was added by @DEAFPS so that user can enable god-mode for them if they want so that it is not enabled by default.

Fair enough, personally as a user I don't see a reason to have god mode disabled by default, not to mention a god mode means you can't see how much damage is applied, from a tall drop or from a nade, etc. `buddha` solves that problem

**Comment by shobhit-pathak** [comment]
Thanks for the explanation, makes sense!

> This sounds great, although we still have the prior collision issues, so this PR is futureproof.

This is true, we had to get these collision stuff sorted, so thanks a lot for this!

I think this seems good-to-go, I'll just test this on my end as well. Could you please change its branch from `main` to `dev` as well?
I'm trying to keep `main` code updated with the current release code for now until I find a better solution or write a pipeline for auto-release :P 

Thanks a lot! :D

**Comment by ar1a** [comment]
definitely much prefer the dev/main branch workflow you're working on now!

**Comment by mrc4tt** [comment]
@ar1a do you plan to add botplace, botboost as examples.

**Comment by ar1a** [comment]
i didn't but I might add .boost now you've mentioned it. .cboost and .cbot can't be implemented yet

**Comment by mrc4tt** [comment]
> i didn't but I might add .boost now you've mentioned it. .cboost and .cbot can't be implemented yet

Oh, so .cboost/cbot isn't possible yet?

How about place, where you aim at X where you want the bot to be placed.
Example: you are on dust2 (short) target xbox to place the bot there e.g.

**Comment by ar1a** [comment]
@mrc4tt where'd you find this snippet?

**Comment by ar1a** [comment]
@shobhit-pathak i think this PR is ready to be reviewed + merged, and i'll add .boost, etc in a separate PR

**Comment by mrc4tt** [comment]
> @mrc4tt where'd you find this snippet?

@ar1a I found it from this: https://github.com/CHR15cs/CS2-Practice-Plugin/blob/c8a3ed382da39254747eba8055de4413ba33c787/CSPracc/Managers/BotManager.cs#L77

Probably not working, as I took this screenshot after testing (yesterday)
image

**Review by shobhit-pathak — APPROVED** [review]
LGTM!

**Pull request merged**
