### PR TITLE
Add full support for Get5 `get5_status` spec

### PR DESCRIPTION
**Pull request by The0mikkel**
Add full support for Get5 `get5_status` spec.

This updates the current `get5_status` command, to respond with the full Get5 schema for the command.
This complements #86

I want to note, that I have not fully tested it, but I have run a small wingman tournament with it.
Had some issues testing, due to the knife round bug.

I am *very* sorry for the split update on `get5_status`

### CODE REVIEW

**Comment by shobhit-pathak** [comment]
Hey!

Thanks a lot for the PR and your work :D

Apologies for not including this PR in 0.7.0 version, as that update was already ready to be pushed. But I'll test it and release it in the next update, that is, 0.7.1 :D 

Thanks!

**Comment by The0mikkel** [comment]
Amazing! You're welcome :D

It definitely needs some testing, as the updates changes some small items in the rest of the codebase.

**Comment by shobhit-pathak** [comment]
Hey!
Could you please check the conflicts?
I had made some minor changes, like fixing naming of the function hence the conflicts in this PR

**Comment by The0mikkel** [comment]
Thank you for highlighting the conflict.  
I will try to take a look at it later today.

**Comment by The0mikkel** [comment]
Just as an update, the update should be ready.
It has been tested at a LAN party event, but I haven't tested it with the newer and more advanced practice setup.

**Review by shobhit-pathak — APPROVED** [review]
Thanks for the PR! This was much needed :D

**Pull request merged**
