### PR TITLE
Fix segmentation fault on map switch after in-game veto

### PR DESCRIPTION
**Pull request by milkywayfarer**
Based on #189 

- Moved `StartDemoRecording()` call to `StartLive()` function, as this is the most suitable location to start recording a demo.
- Codestyling fixes applied automatically on file save.
- Various fixes to demo recording and match states.

Tested out on Linux server with full BO3 correctly played and recorded (including in-game mapveto).

### CODE REVIEW

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for the PR!
Can you help me what all changes are there in "Various fixes to demo recording and match states."? Due to so many formatting changes, I'm not able to see those :P

**Comment by shobhit-pathak** [comment]
Seems like some conflicts came in because of the formatting changes 😅
I will pick the changes directly from #189, apologies for messing up :(

**Comment by milkywayfarer** [comment]
Hey @shobhit-pathak!

Actual changes are:

- `DemoManagement.cs`: `isDemoRecording = false;` after `tv_stoprecord`
- `Utility.cs`:
  1. `matchStarted = true;` removed from `StartKnifeRound()`
  2. `StartDemoRecording();` added after `SetupLiveFlagsAndCfg();` in `StartLive()`
  3. `StartDemoRecording();` removed from `if (isKnifeRequired)` in `HandleMatchStart()`

Literally everything else is formatting :D

**Comment by shobhit-pathak** [comment]
Hey!

Thanks a lot! So do we not need the knife round in the demo?

**Comment by milkywayfarer** [comment]
> Hey!
> 
> Thanks a lot! So do we not need the knife round in the demo?

I would think the knife round being in demo is what breaks the recording. Specifically, the restart that happens before the match hits live. We tested out retaining the knife in the demo, knife plays through, but sometime after it goes live, the server crashes.

Let me know if you want to retain the knife part in the demo. I believe it would make this PR closed, because if we want the knife round, the server will still crash.

**Comment by shobhit-pathak** [comment]
Yeah makes sense, lets leave out the knife round for now.
Thanks for the PR!

**Pull request merged**
