### PR TITLE
Make MatchID int ( #164 )

### PR DESCRIPTION
**Pull request by FlowingSPDG**
context: #164 

Originally get5 matchid WAS int, and supported string afterwards.

Now MatchZy only supports integer, However its definitions is string so I fixed them :)

### CODE REVIEW

**Comment by shobhit-pathak** [comment]
Hey!

Thanks for the PR. A quick question, can G5API accept matchid as an integer or does it still needs to be a string?

**Comment by FlowingSPDG** [comment]
@shobhit-pathak Hi again!
I think it already accepts both of int and string since its ``any`` type on TypeScript?
https://github.com/PhlexPlexico/G5API/blob/20727f19ab9cf145257f777bf7e4954e14a1b7a7/src/routes/v2/api.ts#L88

Also matchID is defined as generic type for ``string | number`` so I believe it will be okay
https://github.com/PhlexPlexico/G5API/blob/20727f19ab9cf145257f777bf7e4954e14a1b7a7/src/utility/utils.ts#L509-L516

**Comment by shobhit-pathak** [comment]
Thanks for the confirmation!

**Comment by FlowingSPDG** [comment]
Thank you for merging this!
I think I forgot to change one thing here: https://github.com/shobhit-pathak/MatchZy/blob/a3a34e358eafed20c910dcc0b0fc7f5239ff1b34/DemoManagement.cs#L117

It's better to change it to long/integer imo but if you're worrying about back-compatibility I guess we can leave it string

**Pull request merged**
