### PR TITLE
Chat Color Messages

### PR DESCRIPTION
**Pull request by sniperpl**

### CODE REVIEW

**Comment by shobhit-pathak** [comment]
Hey!
Thanks for the PR, can we use the colors from ChatColors class rather than directly using their cods? Like `ChatColors.Green`, `ChatColors.Default`, etc.

**Comment by shobhit-pathak** [comment]
Hey!
Thanks a lot for covering the remaining translation strings, helps a lot!
I'll soon review the PR

**Comment by shobhit-pathak** [comment]
Hey @sniperpl 
Is it ready to merge?

**Comment by sniperpl** [comment]
For me yeah.

**Review by shobhit-pathak — APPROVED** [review]
Thanks a lot for adding the remaining strings!

**Pull request merged**
