### PR TITLE
Add Chinese (Simplified) Translate by MerakW

### PR DESCRIPTION
**Pull request by MerakW**
This translation is translated by myself, if you have any questions, comments are welcomed.

### CODE REVIEW

**Comment by JammyLin** [comment]
个人拙见，既然是我们自己看的，可以翻译的简单一些，比如'您已成功准备'，‘您已"取消"准备’，'比赛恢复'，'取消暂停'之类的。
另外，你的文件名是错误的。可以直接改成zh.json

**Comment by JammyLin** [comment]
其实也可以自己增加颜色来更醒目，例如
您已{green}准备{default}！
您已{red}取消准备{default}！
我不知道前面颜色是否可以自行更改，毕竟我也不会这语言。

To Author or maintainer:
Is it possible to change the colour code to a specific colour at will?  Support for Hex?

**Comment by MerakW** [comment]
> 个人拙见，既然是我们自己看的，可以翻译的简单一些，比如'您已成功准备'，‘您已"取消"准备’，'比赛恢复'，'取消暂停'之类的。 另外，你的文件名是错误的。可以直接改成zh.json

翻译确实言之有理，但是我个人翻译的时候还是觉得需要保持原意是最合理的，不去打破原本的内容
至于文件名，zh-cn（中国大陆中文）确实有误，现在应该用zh-hans，代表中文简体中文。

**Comment by JammyLin** [comment]
文件名依旧不对。它是RFC 4646格式，所以后一个单词要大写，比如zh-Hans

**Comment by shobhit-pathak** [comment]
Hey, thanks for the PR!
As @JammyLin, should the file name be `zh-Hans.json`?

**Comment by MerakW** [comment]
I'm really sorry that I didn't submit my changes until today, I was so busy a while ago that I didn't pay attention to the Github content. @shobhit-pathak

**Review by JammyLin — APPROVED** [review]

**Review by JammyLin — APPROVED** [review]

**Comment by JammyLin** [comment]
To be honest, I don't really understand whether it needs to be reviewed by others or by the maintainer, at least I think the translation is pretty good.
Then I checked the code, is it possible to internationalise all strings later? It looks like it's possible.

**Comment by MerakW** [comment]
@JammyLin I agree with your opinion about other strings, there is still a lot strings didn't translated.

**Comment by shobhit-pathak** [comment]
Hey!

Yes there's still a lot of strings present for which translation is needed. The idea was to set-up the base of translation with some strings. I'll soon release an update in which I'll try to cover the remaining strings so that we have complete translation available.

Thanks!

**Comment by MerakW** [comment]
It means my pr will be merged after full translate right? @shobhit-pathak

**Comment by shobhit-pathak** [comment]
Merged it, thanks for the translations! :D

**Comment by MerakW** [comment]
I'm happy to contribute to such a great open source project!

> Merged it, thanks for the translations! :D

**Pull request merged**
